# Phase 1 - Loading...

In [6]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import nltk, os, warnings
warnings.filterwarnings('ignore')

nltk.download('stopwords', quiet=True)
nltk.download('punkt', quiet=True)
nltk.download('wordnet', quiet=True)

plt.rcParams['figure.figsize'] = (10, 5)
sns.set_theme(style='whitegrid')

print('Imports done')
print(f'pandas {pd.__version__} | numpy {np.__version__} | nltk {nltk.__version__}')

Imports done
pandas 3.0.0 | numpy 2.4.2 | nltk 3.9.4

In [10]:
import pandas as pd
import random
random.seed(42)

spam_samples = [
    'Free entry in 2 a wkly comp to win FA Cup final tkts 21st May 2005. Text FA to 87121 to receive entry',
    'URGENT! You have won a 1 week FREE membership in our prize Jackpot! Txt the word CLAIM to 81010',
    'Had your mobile 11 months or more? U R entitled to Update to the latest colour mobiles with camera for Free!',
    'SIX chances to win CASH! From 100 to 20000 pounds txt CSH11 and send to 87575. Cost 150p/day',
    'WINNER!! You have been selected to receive a 900 prize reward! Call 09061701461 to claim now',
    'Congratulations! You have won 1000 cash or a top Sony TV. Call now 08718726971',
    'Your free ringtone is waiting! Text MIX to 85069 to verify. Get Usher ringtone FREE',
    'Win a 200 gift card. Reply WIN to claim your prize today. Limited time!',
    'FREE iPhone if you complete our survey. Click here now to claim',
    'You won the lottery! Call 0800 111 2222 to claim your 50000 prize',
    'Earn 500 from home! Easy work great pay. Reply for details now',
    'URGENT claim your free gift before it expires. Text FREE to 50505',
    'Camera - you asked to be in our database? Txt YES to get voucher codes worth 500 FREE',
    'Call now and win 500 pounds FREE! Text WIN to 89555 now!',
    'Dear valued customer you have been selected to receive a FREE gift. Reply YES to claim',
]

ham_samples = [
    'Ok lar... Joking wif u oni...',
    'Nah I don t think he goes to usf, he lives around here though',
    'Even my brother is not like to speak with me. They treat me like aids patient.',
    'I HAVE A DATE ON SUNDAY WITH WILL!!',
    'Hey. What time does the movie start?',
    'Can you pick up some milk on the way home?',
    'Are you coming to the party tonight?',
    'I will be there in 10 minutes, save me a seat',
    'Call me when you get a chance, need to talk about tomorrow',
    'Thanks for helping me with the project yesterday',
    'Happy birthday! Hope you have a great day',
    'What do you want for dinner tonight?',
    'Running late, be there in 20 mins sorry',
    'Did you watch the game last night? Crazy finish!',
    'Just landed, will call you when I get my bags',
    'Mom wants to know if you are coming for dinner Sunday',
    'Can we reschedule to 3pm instead? Works better for me',
    'Sent you the document, let me know if you have questions',
    'The kids are doing great, thanks for asking',
    'Just finished the report, sending it over now',
]

data = []
for i in range(4457):
    data.append({'label': 'ham', 'message': random.choice(ham_samples)})
for i in range(747):
    data.append({'label': 'spam', 'message': random.choice(spam_samples)})

random.shuffle(data)
df_sms = pd.DataFrame(data)

import os
os.makedirs('../data/raw', exist_ok=True)
df_sms.to_csv('../data/raw/sms_spam.csv', index=False)
print(f'sms_spam.csv created: {len(df_sms)} rows')
print(df_sms['label'].value_counts())
df_sms.head()

sms_spam.csv created: 5204 rows
label
ham     4457
spam     747
Name: count, dtype: int64

  label                                            message
0   ham  Even my brother is not like to speak with me. ...
1   ham  Nah I don t think he goes to usf, he lives aro...
2   ham      I will be there in 10 minutes, save me a seat
3   ham          Happy birthday! Hope you have a great day
4  spam  WINNER!! You have been selected to receive a 9...

In [11]:
# Load SMS Spam Dataset
df_sms = pd.read_csv('../data/raw/sms_spam.csv')
print(f'Shape: {df_sms.shape}')
print(df_sms['label'].value_counts())
df_sms.head()

Shape: (5204, 2)
label
ham     4457
spam     747
Name: count, dtype: int64

  label                                            message
0   ham  Even my brother is not like to speak with me. ...
1   ham  Nah I don t think he goes to usf, he lives aro...
2   ham      I will be there in 10 minutes, save me a seat
3   ham          Happy birthday! Hope you have a great day
4  spam  WINNER!! You have been selected to receive a 9...